### ISSUE TITLE
ArrayPorts assignment order changes  randomly between runs

### ISSUE THREAD

**Issue by krylovsk** [cascades-fbp/cascades#17]
For example, for this FBP network:
AirSensorProp PROP -> DATA[0] ContextA
WindowProp PROP -> DATA[1] ContextA
MotionProp PROP -> DATA[2] ContextA

The resulting assignment can be:
AirSensorProp PROP -> DATA[2] ContextA
WindowProp PROP -> DATA[0] ContextA
MotionProp PROP -> DATA[1] ContextA

**Comment by oleksandr** [comment]
Reproducible with flow:

'0' -> IN[0] Mux(core/joiner)
'1' -> IN[1] Mux(core/joiner)
'2' -> IN[2] Mux(core/joiner)
'3' -> IN[3] Mux(core/joiner)
Mux OUT -> IN Log(core/console)

Results in (after several runs):

Mux     | Data from port IN[3]: "0"
Mux     | Data from port IN[0]: "1"
Mux     | Data from port IN[1]: "2"
Mux     | Data from port IN[2]: "3"

**Comment by krylovsk** [comment]
After quick tests, the update seems to have fixed the issue.
