### ISSUE TITLE
Little error in wiki/Installing-from-sources

### ISSUE THREAD

**Issue by jibe-b** [cascades-fbp/cascades#18]
Hi,

in the installation instructions ( https://github.com/cascades-fbp/cascades/wiki/Installing-from-sources )

this:

> GOPATH=`pwd` go get -d github.com/cascades-fbp/cascades.git

should be replaced by:

> GOPATH=`pwd` go get -d github.com/cascades-fbp/cascades

(remove the ".git" suffix)

Otherwise, the error:
package github.com/cascades-fbp/cascades.git: invalid version control suffix in github.com/ path

similar problem + solution:
https://github.com/hooklift/golibvirt/issues/10

**Comment by oleksandr** [comment]
Thanks! Fixed it :)
