### ISSUE TITLE
cannot register component … fork/exec /home/jibe/test-cascades/gmxhelp: permission denied

### ISSUE THREAD

**Issue by jibe-b** [cascades-fbp/cascades#20]
Hi,

I try to add a component to the library.

From the cascades/ folder, I run

> ./cascades library add --name="test/component" /home/me/component

and it is returned:

> Failed to add a component: Cannot register component test/component: fork/exec /home/me/component: permission denied

Thanks for helping.

Best regards.

**Comment by krylovsk** [comment]
is your component executable?
try chmod a+x /home/me/component

**Comment by jibe-b** [comment]
it was not. Thanks!

Maybe could it be added to the wiki, in order to make it easy for beginners?
